remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

lang:  en
title: Alexander Moore

description: >
  Former A.I. Research Scientist at Lawrence Livermore National Laboratory.
  Writing about computer vision, autonomous vehicles, and independent research.

tagline: Computer Vision & AV Research

logo: /images/thumbnail_Image.jpg

author:
  name: Alexander Moore

menu:
  - title: About
    url: /
  - title: Blog
    url: /blog
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=Uq_mfNsAAAAJ&hl=en&oi=sra
  - title: GitHub
    url: https://github.com/alexander-moore

accent_color: rgb(38, 80, 115)
theme_color:  rgb(25, 55, 71)
accent_image:
  background: rgb(25, 55, 71)
  overlay:    false

hydejack:
  no_search:           true
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  hide_last_modified:  true
  dark_mode:
    always:  false
    dynamic: true
    icon:    true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

markdown: kramdown
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
